---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mealie-local-data
  namespace: prod
  labels:
    directory: mealie-data
spec:
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local
  local:
    path: /var/mealie-data
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - xaf-agent-01
