---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mealie-local-data-claim
  namespace: prod
spec:
  storageClassName: local
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      directory: mealie-data
