---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-local-data
  namespace: prometheus
  labels:
    directory: prometheus-data
spec:
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local
  local:
    path: /media/external-drive/prometheus-data
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
            - xaf-agent-01
