apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: traefik-argocd
  namespace: argocd
spec:
  ingressClassName: traefik
  rules:
  - host: argocd.home
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: argocd-server
            port:
              name: http
