---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: actualbudget-local-data-claim
  namespace: actualbudget
spec:
  storageClassName: local
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      directory: actualbudget-data
