---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: actualbudget-local-data
  namespace: actualbudget
  labels:
    directory: actualbudget-data
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local
  local:
    path: /var/actualbudget-data
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - xaf-agent-01
